name: Release

on:
  push:
    tags:
      - 'v*'

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - run: npm install -g @tauri-apps/cli
    - run: npm install
    - run: tauri build
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/**/*.sig
          src-tauri/target/release/bundle/**/*